name = "bugscraper"
default_targets = ["win64", "appimage"]
build_directory = "export"
icon_file = "icon.png"

love_files = [
    "+*",
    "-*/.*",
    "-./export/*",
]

[hooks]
prebuild = [
	"make all_release",
]

[windows]
[win32]
shared_libraries = [
	"lib/midi_input_handler/libmidi_input_handler.dll",
]

[appimage]

shared_libraries = [
	"lib/midi_input_handler/libmidi_input_handler.so",
]