name = "bugscraper"
default_targets = ["win32", "win64", "lovejs", "appimage"]
build_directory = "bugscraper-export"
icon_file = "icon.png"

love_files = [
    "+*",
    "-*/.*",
    "-./bugscraper-export/*",
]
