name = "bugscraper"
default_targets =["appimage" ]#["win64", "appimage","macos,"]
build_directory = "export"
icon_file = "icon.png"

love_files = [
    "+*",
    "-*/.*",
    "-./export/*",

#midi input source code
    "-./lib/midi_input_handler/src/*",
    "-./lib/midi_input_handler/target/*",
    "-./lib/midi_input_handler/Cargo.lock",
    "-./lib/midi_input_handler/Cargo.toml",
    "-./lib/midi_input_handler/makefile",
]

[hooks]
prebuild = [
	"make all_release",
]

[windows]
[win32]
shared_libraries = [
	"lib/midi_input_handler/libmidi_input_handler.dll",
]

[appimage]

shared_libraries = [
	"lib/midi_input_handler/libmidi_input_handler.so",
]