name = "bugscraper_0.4_midi_dev"
default_targets =["appimage", "win64" ]#["win64", "appimage","macos,"]
build_directory = "export"
icon_file = "icon.png"
keep_game_directory = false

love_files = [
    "+*",
    "-*/.*",
    "-./export/*",

#midi input source code
    "-./lib/midi_input_handler/src/*",
    "-./lib/midi_input_handler/target/*",
    "-./lib/midi_input_handler/Cargo.lock",
    "-./lib/midi_input_handler/Cargo.toml",
    "-./lib/midi_input_handler/makefile",

#other files
    "-./makefile",
    "-./makelove_example.toml",
    "-./scripts/_trash.lua",


#asesprite file
    "-*.aseprite"
]

[hooks]
prebuild = [
	"make all_release",
]

postbuild = [
    "cp ./lib/midi_input_handler/libmidi_input_handler.so  ./export/appimage/libmidi_input_handler.so",
    "echo '\n<== DONE ==>\n'"
]

[windows]
[windows.archive_files]
[win64]
shared_libraries = [
	"./lib/midi_input_handler/midi_input_handler.dll",
]

[appimage]

artifacts = "appimage" 

[lovejs]
title = "Bugscraper"  # used on the resulting web page
memory = "40000000"  # starting memory of the webpage (default is 20 MB)