name = "bugscraper"
default_targets = ["win32", "win64", "appimage", "lovejs", "macos"]
build_directory = "export"
icon_file = "icon.png"

love_files = [
    "+*",
    "-*/.*",
    "-./bugscraper-export/*",
]
