name = "bugscraper"
default_targets = []
build_directory = "export"
icon_file = "icon.png"

love_files = [
    "+*",
    "-*/.*",
    "-./export/*",
]

shared_libraries = [
    "lib/midi_input_handler/libmidi_input_handler"
]