name = "bugscraper"
default_targets =["appimage" ]#["win64", "appimage","macos,"]
build_directory = "export"
icon_file = "icon.png"
keep_game_directory = false

love_files = [
    "+*",
    "-*/.*",
    "-./export/*",

#midi input source code
    "-./lib/midi_input_handler/src/*",
    "-./lib/midi_input_handler/target/*",
    "-./lib/midi_input_handler/Cargo.lock",
    "-./lib/midi_input_handler/Cargo.toml",
    "-./lib/midi_input_handler/makefile",

#other files
    "-./makefile",
    "-./makelove_example.toml",
    "-./scripts/_trash.lua",
]

[hooks]
prebuild = [
	"make all_release",
]

[archive_files]
"lib.midi_input_handler.libmidi_input_handler.so" = "libmidi_input_handler.so"

[windows]
[windows.archive_files]
[win32]
shared_libraries = [
	"./lib/midi_input_handler/libmidi_input_handler.dll",
]

[appimage]
[appimage.hooks]
prebuild = [
    "echo --------------------------------------------------------------------------------------------------------------------------------"
]
artifacts = "appimage" 

shared_libraries = [
	"./lib/midi_input_handler/libmidi_input_handler.so",
]

